apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: workshop
spec:
  selector:
    app: mongo
  ports:
    - name: mongo-svc
      protocol: TCP
      port: 27017
      targetPort: 27017

